config/routes.rb
Rails.application.routes.draw do
  root 'homes#home'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users
  resources :books
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true
  validates :title, :body, length: { in: 1..200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name,
  length: { minimum: 2, maximum: 20, message: "is too short (minimum is 2 characters)" }
  validates :introduction,
  length: { maximum: 50, message: "is too long (maximum is 50 characters)" }
  
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    users_path and return
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  def index
    @book =Book.new
    @books = Book.all
    @user = current_user
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
    if @book.save
  	   redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
  def about
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  def index
  	@book =Book.new
  	@users = User.all
    @user = current_user
  end
  def show
  	@book = Book.new
  	@user = User.find(params[:id])
  	@books = @user.books.all
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <% if @book.errors.any? %>
      <p id="notice">
        <div id="error_explanation">
          <h3>
            <%= pluralize(@book.errors.count, "error") %> error prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </p>
    <% end %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
		    <h1>Editing Book</h1>
		    <%= form_for(@book) do |f| %>
          <div class="field row">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"col-xs-12 book_title" %>
          </div>
          <div class="field row">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"col-xs-12 book_body" %>
          </div>
          <div class="actions row">
            <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %> |
    		<%= link_to "Back",books_path %>
      </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">
    <% if @book.errors.any? %>
      <p id="notice">
        <div id="error_explanation">
          <h3>
            <%= pluralize(@book.errors.count, "error") %> error prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </p>
    <% end %>
    <!-- ここからユーザー情報 -->
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th>
                <%= @user.name %>
              </th>
            </tr>
            <tr>
              <th>introduction</th>
              <th>
                <%= @user.introduction %>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to " ", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
        </div>
        <!-- ここまでユーザー情報 -->
        <h2>New book</h2>
        <!-- ここからが投稿ページ -->
        <%= form_for(@book) do |f| %><!-- form_for記入 -->
          <div class="field row">
            <label for="book_title">Title</label>
              <%= f.text_field :title, class:"col-xs-12" %>
          </div>
          <div class="field row">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"col-xs-12" %>
          </div>
          <div class="actions row">
            <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
      </div>
      <!-- 右側ページ -->
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><!-- userアイコン&リンク挿入 -->
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:'40x40' %>
                    <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book) %><!-- Title -->
                </td>
                <td>
                  <%= book.body %><!-- Opinion -->
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="body">
  <div class="container">
    <p id="notice">
      <%= notice %>
    </p>
    <!-- ここからユーザー情報 -->
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= link_to attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th>
                <%= @book.user.name %>
              </th>
            </tr>
            <tr>
              <th>introduction</th>
              <th>
                <%= @book.user.introduction %>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to " ", edit_user_path(@book.user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
        </div>
        <!-- ここからが投稿ページ -->
        <h2>New book</h2>
        <%= form_for(@new_book) do |f| %><!-- form_for記入 -->
          <div class="field row">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"col-xs-12" %>
          </div>
          <div class="field row">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"col-xs-12" %>
          </div>
          <div class="actions row">
            <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %><!-- ここまで投稿ページ -->
      </div>
<!-- 右側ページ -->
      <div class="col-xs-9">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book) %><!-- Title -->
              </td>
              <td>
                <%= @book.body %><!-- Opinion -->
              </td>
              <% if @book.user == current_user %>
                <td>
                    <%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success edit_book_34534" %>
                </td>
                <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn-sm btn-danger destroy_book_34534" %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="body">
<div class="container">
	<div class="row">
		<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
	</div>
</div>

app/views/homes/home.html.erb
<div class="body">
  <div class="container">
      <p id="notice">
        <%= flash[:notice] %>
      </p>
      <div class="row">
      <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
      <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper">
        <div class="row">
          <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
        </div>
        <div class="row">
          <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- header -->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li>
                <%= link_to "Home", user_path(current_user.id), class:"glyphicon glyphicon-home home" %>
                </li>
                <li>
                <%=link_to "Users", users_path, class:"glyphicon glyphicon-user users" %>
                </li>
                <li><%= link_to "Books", books_path, class:"glyphicon glyphicon-book books" %>
                </li>
                <li>
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out logout" %>
                </li>
              <% else %>
                <li>
                <%= link_to "Home", root_path, class:"glyphicon glyphicon-home home" %>
                </li>
                <li>
                <%= link_to "About", home_about_path, class:"glyphicon glyphicon-link about" %>
                </li>
                <li>
                  <%= link_to "sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %>
                </li>
                <li>
                  <%= link_to "login", new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %>
                </li>
              <% end %>
            </ul>
        </nav>
      </div>
    </header>
    <!-- header -->
    <%= yield %>
    <!-- footer -->
    <footer>
      <div class="container">
        <div class="row">
          </div>
        </div>
      </div>
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-xs-3 col-xs-offset-9">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
    <% if @user.errors.any? %>
      <p id="notice">
        <div id="error_explanation">
          <h3>
            <%= pluralize(@user.errors.count, "error") %> error prohibited this obj from being saved:
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </p>
    <% end %>
    <p id="notice"></p>

    <h2>User info</h2>
    <%= form_for(@user) do |f| %>
      <div class="field">
        <label for="user_name">Name</label>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="field">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction %>
      </div>
      <div class="actions">
        <%= f.submit "Update User" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <% if @book.errors.any? %>
      <p id="notice">
        <div id="error_explanation">
          <h3>
            <%= pluralize(@book.errors.count, "error") %> error prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </p>
    <% end %>
    <!-- ここからユーザー情報 -->
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th>
                <%= @user.name %>
              </th>
            </tr>
            <tr>
              <th>introduction</th>
              <th>
                <%= @user.introduction %>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to " ", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
        </div>
        <!-- ここからが投稿ページ -->
        <h2>New book</h2>
        <%= form_for @book, :url => {controller: "books", action: "create"} do |f| %>
          <div class="field row">
            <label for="book_title">Title</label>
              <%= f.text_field :title, class:"col-xs-12" %>
          </div>
          <div class="field row">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"col-xs-12" %>
          </div>
          <div class="actions row">
            <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
      </div>
      <!-- 右側ページ -->
      <div class="col-xs-9">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><!-- userアイコン&rリンク挿入 -->
                  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:'40x40' %>
                </td>
                <td>
                  <%= user.name %><!-- user -->
                </td>
                <td>
                  <%= link_to "Show", user_path(user) %><!-- shoe -->
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body">
  <div class="container">
    <p id="notice">
      <%= notice %>
    </p>
    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@book.errors.count, "error") %> error prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </p>
    <% end %>
    <!-- ここからユーザー情報 -->
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th>
                <%= @user.name %>
              </th>
            </tr>
            <tr>
              <th>introduction</th>
              <th>
                <%= @user.introduction %>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to " ", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
        </div>
        <!-- ここからが投稿ページ -->
        <h2>New book</h2>
        <%= form_for @book, :url => {controller: "books", action: "create"} do |f| %><!-- form_for記入 -->
          <div class="field row">
            <label for="book_title">Title</label>
              <%= f.text_field :title, class:"col-xs-12" %>
          </div>
          <div class="field row">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"col-xs-12" %>
          </div>
          <div class="actions row">
            <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
      </div>
      <!-- 右側ページ -->
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><!-- userアイコン&rリンク挿入 -->
                  <%= link_to(attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:'40x40') %>
                <td>
                  <%= link_to book.title, book_path(book) %><!-- title -->
                </td>
                <td>
                  <%= book.body %><!-- shoe -->
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>